kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: 0
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ConfigMap.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: index-html
          configMap:
            name: '{{ .Chart.Name }}-html'
            defaultMode: 420
      containers:
        - resources: {}
          env:
          - name: PORT
            value: {{ .Values.containers.containerPort | quote }}
          volumeMounts:
          - name: index-html
            mountPath: {{ .Values.volume.mount.path }}

          terminationMessagePath: /dev/termination-log
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          readinessProbe:
            {{- tpl (toYaml .Values.Probes.readiness) . | nindent 12 }}
          livenessProbe:
            {{- tpl (toYaml .Values.Probes.liveness) . | nindent 12 }}

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10