ReplicaNumber: 1
containers:
  containerPort: 8080
  image: 'quay.io/galpeer/simpleexpress'
  tag: 'chart_v1'

service:
  servicePort: 8080

Probes:
  readiness:
    httpGet:
      path: /health/readiness # this check the application url path
      port: 8080 # In which port the Application is listening
      scheme: HTTP
    initialDelaySeconds: 1 # the time is waiting befor testing the application path
    timeoutSeconds: 1 # the time for timeout
    periodSeconds: 10 # the abount of time to wait between checks
    successThreshold: 1 # count to decalre seccessfull 
    failureThreshold: 3 # count to decalre failure           
  liveness:
    httpGet:
      path: /health/liveliness # this check the application url path
      port: 8080 # In which port the Application is listening
      scheme: HTTP
    initialDelaySeconds: 1 # the time is waiting befor testing the application path
    timeoutSeconds: 1 # the time for timeout
    periodSeconds: 10 # the abount of time to wait between checks
    successThreshold: 1 # count to decalre seccessfull 
    failureThreshold: 3 # count to decalre failure      